### ISSUE TITLE
Ensure WebMap version compatibility

### ISSUE THREAD

**Issue by phreed** [FreeTAKTeam/FreeTAKHub-Installation#115] opened 2024-03-27 16:27 UTC
Identify compatible versions of `node-red` and `webmap`.
Select one of these compatible pairs and lock in their versions during installation.

**Comment by brothercorvo** [comment] 2024-03-27 18:49
the issue is the version of NodeRed, we should test if an upgrade of nodered would fix the issue with the WorldNap library

**Comment by ki6uve** [comment] 2024-03-28 23:16
I have confirmed that upgrading Node-RED does indeed fix the "node type" error that is occurring in 'node-red-contrib-web-worldmap' module of Node-RED after fresh ZTI of FTS.  I used this command to upgrade to version 20 of Node-RED and then reenabled/restarted Node-RED service as a work around:

bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) --node20

**Comment by brothercorvo** [comment] 2024-03-29 12:48
> I have confirmed that upgrading Node-RED does indeed fix the "node type" error that is occurring in 'node-red-contrib-web-worldmap' module of Node-RED after fresh ZTI of FTS. I used this command to upgrade to version 20 of Node-RED and then reenabled/restarted Node-RED service as a work around:
> 
> bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) --node20

excellent news! @phreed we need to discuss how to install again the last version of NR

**Comment by brothercorvo** [comment] 2024-10-17 17:15
closing this as we are working on  #120

**Closed by brothercorvo** 2024-10-17 17:15 UTC
Labels: bug
